### ISSUE TITLE
Release to package control

### ISSUE THREAD

**Issue by max-mykhailenko** [pepahlavacek/sublime-react-component-autocomplete#4]
Want to try it and provide for my team. Can you put it to the package control?

**Comment by pepahlavacek** [comment]
Hey Max, thanks for reaching out! I'm sorry but this package is not supported anymore as our team has shifted from coffeescript to es6 and we use different tools now.

I wouldn't feel comfortable having this plugin in package control when I haven't had time to work on it for 2 years. So I'd recommend manual installation for trying it out and if you run into any issues worth fixing, feel free to open a PR and I'll get it in.

**Comment by max-mykhailenko** [comment]
@pepahlavacek do you use sublime? I also use ES6+ and want to organize better autocomplete in Sublime
